WITH SENDERS AS (
    SELECT
        SENDER AS USER_ID,
        SUM(AMOUNT) AS SENDED_AMOUNT
    FROM
        '{table}'
    GROUP BY 
        SENDER
), RECEIVERS AS (
    SELECT
        RECEIVER AS USER_ID,
        SUM(AMOUNT) AS RECEIVED_AMOUNT
    FROM
        '{table}'
    GROUP BY
        RECEIVER
)
FROM
    SENDERS
    FULL OUTER JOIN RECEIVERS ON SENDERS.USER_ID = RECEIVERS.USER_ID
SELECT 
    COALESCE(SENDERS.USER_ID, RECEIVERS.USER_ID) AS USER_ID,
    COALESCE(SENDERS.SENDED_AMOUNT, 0) - COALESCE(RECEIVERS.RECEIVED_AMOUNT, 0) AS NET_CHANGES
