WITH USERS AS (
    FROM
        '{table}'   
    SELECT DISTINCT 
        USER_ID
), TRANSACTIONS AS (
    FROM
        '{table}'
    SELECT 
        USER_ID,
        TRANSACTION_DATE AS DATES,
        ROW_NUMBER() OVER (
            PARTITION BY USER_ID
            ORDER BY TRANSACTION_DATE
        ) AS POSITION
), SUPERS AS (
    FROM
        TRANSACTIONS 
    SELECT 
        TRANSACTIONS.USER_ID,
        TRANSACTIONS.DATES AS DATE_AS_SUPER
    WHERE 
        TRANSACTIONS.POSITION = 2
)
FROM
    USERS
    LEFT JOIN SUPERS ON USERS.USER_ID = SUPERS.USER_ID
SELECT 
    USERS.USER_ID,
    SUPERS.DATE_AS_SUPER
